# Generated by Django 3.2.15 on 2022-09-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_medication_drone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='serialNumber',
            field=models.CharField(db_column='serial_number', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
